# -*- encoding: utf-8 -*-


{
    'name': 'Color Lab Sales',
    'version': '1.0',
    'category': 'Color Lab Sales',
    'author': 'Atees',
    'description': """Sales Management""",
    'summary': '',
    'website': '',
    'images': ['static/description/icon.png'],
    'data': [
        'security/access_groups.xml',
        'security/ir.model.access.csv',
        'security/record_rule.xml',
        'data/data.xml',
        'data/ir_sequence.xml',
        'data/activity_data.xml',
        'wizards/work_flow_change.xml',
        'wizards/correction_report_wizard_views.xml',
        'views/agent_form.xml',
        'views/agent_customer.xml',
        'views/printer_conf.xml',
        'views/brand.xml',
        'views/printer_service_types.xml',
        'views/minibook_conf.xml',
        'views/product.xml',
        'views/work_category.xml',
        'views/operation_work_orders.xml',
        'views/printer_package_view.xml',
        'views/res_config_settings.xml',
        'views/at_product.xml',
        'views/sale_order_inherit.xml',
        'reports/sale_order_report_inherit.xml',
        'reports/correction_report.xml',
        'views/title.xml',
        'views/account_move.xml',
        'views/courier_type.xml',
        'views/sale_order_search_inherit.xml',
    ],
    'depends': ['base', 'contacts', 'sale', 'sale_management', 'hr', 'web_approval', 'uom', 'stock', 'product','account', 'mail',
                'purchase'],
    'assets': {
        'web.assets_backend': [
            '/color_lab_sale/static/src/css/agent_form.css',
        ],
    },
    'installable': True,
    'auto_install': False,
    'application': True,
    'sequence': 105,
    'license': 'AGPL-3',
}
